// playground/react/src/components/navigation.tsx
import { useNavigate } from '@ciderjs/city-gas/react';

export const Navigation = () => {
  const navigate = useNavigate();
  return (
    <nav>
      <button type="button" onClick={() => navigate('/')}>
        Go to Home
      </button>
      <button
        type="button"
        onClick={() => navigate('/users/show', { userId: '123' })}
      >
        Go to Profile 123
      </button>
      <button type="button" onClick={() => navigate('/about')}>
        Go to About
      </button>
    </nav>
  );
};

// playground/vue3/src/components/navigation.vue
<template>
  <nav>
    <button @click="goHome">Go Home</button>
    <button @click="goUser">Go User 123</button>
    <button @click="goAbout">Go About</button>
  </nav>
</template>

<script setup lang="ts">
import { useNavigate } from '@ciderjs/city-gas/vue';

const navigate = useNavigate();

const goHome = () => navigate('/');
const goUser = () => navigate('/users/show', { userId: '123' });
const goAbout = () => navigate('/about');
</script>
