// playground/src/App.tsx
import React from 'react';
import {
  createRouter,
  RouterProvider,
  useNavigate,
  RouterOutlet,
} from 'city-gas';
import type { RouteNames, RouteParams } from './generated/router.d';
import { pages } from './generated/routes';

// 1. 生成された pages マップをルーターに渡す
const router = createRouter<RouteNames, RouteParams>(pages, { defaultRouteName: '' });

// 2. ナビゲーションUI
const Navigation = () => {
  const navigate = useNavigate();
  return (
    <nav>
      <button onClick={() => navigate('', {})}>Go to Home</button>
      <button onClick={() => navigate('users/show', { userId: '123' })}>Go to Profile 123</button>
      <button onClick={() => navigate('about', {})}>Go to About</button>
    </nav>
  );
};

function App() {
  return (
    <RouterProvider router={router}>
      <h1>city-gas Playground</h1>
      <Navigation />
      <hr />
      <RouterOutlet />
    </RouterProvider>
  );
}

export default App;

// playground/vue3/src/App.vue
<template>
  <div>
    <h1>city-gas Vue Playground</h1>
    <nav>
      <button @click="goHome">Go Home</button>
      <button @click="goUser">Go User 123</button>
      <button @click="goAbout">Go About</button>
    </nav>
    <hr />
    <RouterOutlet />
  </div>
</template>

<script setup lang="ts">
import { useNavigate, RouterOutlet } from "@ciderjs/city-gas/vue";

const navigate = useNavigate();

const goHome = () => navigate("/");
const goUser = () => navigate("/users/show", { userId: "123" });
const goAbout = () => navigate("/about");
</script>
