// playground/vue3/src/pages/users/show.vue
<template>
  <div>
    <h2>User Show Page</h2>
    <p>Tab ID: {{ ref.tab }}</p>
  </div>
</template>

<script setup lang="ts">
import { useParams } from '@ciderjs/city-gas/vue';

const ref = useParams('/users/show');
</script>

<script lang="ts">
import { z } from 'zod';
export const schema = z.object({
  tab: z.string(),
});
</script>

// playground/react/src/pages/users/show.tsx
import { useParams } from '@ciderjs/city-gas/react';
import { z } from 'zod';

export const schema = z.object({
  tab: z.string(),
});

export default function UserShowPage() {
  const { tab } = useParams('/users/show');
  return (
    <div>
      <h2>User Show Page</h2>
      <p>Tab ID: {tab}</p>
    </div>
  );
}
